## CodeBook

The original data for the analysis was downloaded from this link: https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

This document is intended to inform about the different variables in the output file i.e. Tidy_Data.csv that gets generated after running the script.

The variables prefixed with "t" represent a time domain measurement whereas the ones prefixed with "f" represents the measurements that were Fourier Transformed. Each of the measurement have been divided by its range (gyroscope, entropy, etc) and therefore the unit associated with each of the measurements gets cancelled and the left over numeric value just represents a ratio.

| VARIABLES     | DESCRIPTION           | VALUES     |
| ------------- |:---------------------:| ----------:|
| Subjects      | Stores the subject ids| Range 1-30 |
| Activity      | Stores information on the activity performed by the subject | Walking/Walking Up/Walking Down/Standing/Sitting/Laying|
| tBodyAcc_mean_X |  Mean of the body acceleration from X-Axis| Numeric Value|
| tBodyAcc_mean_Y |  Mean of the body acceleration from Y-Axis| Numeric  Value|
| tBodyAcc_mean_Z |  Mean of the body acceleration from Z-Axis| Numeric Value|
| tBodyAcc_std_X  |  Standard Deviation of the body acceleration from X-Axis| Numeric Value|
| tBodyAcc_std_Y  |  Standard Deviation of the body acceleration from Y-Axis| Numeric Value|
| tBodyAcc_std_Z  |  Standard Deviation of the body acceleration from Z-Axis| Numeric Value| 
| tGravityAcc_mean_X | Mean of the gravity acceleration from X-Axis| Numeric Value|
| tGravityAcc_mean_Y | Mean of the gravity acceleration from Y-Axis| Numeric Value|
| tGravityAcc_mean_Z | Mean of the gravity acceleration from Z-Axis| Numeric Value|
| tGravityAcc_std_X |  Standard Deviation of the gravity acceleration from X-Axis| Numeric Value|
| tGravityAcc_std_Y |  Standard Deviation of the gravity acceleration from Y-Axis| Numeric Value|
| tGravityAcc_std_Z |  Standard Deviation of the gravity acceleration from Z-Axis| Numeric Value|
| tBodyAccJerk_mean_X | Mean of the Jerk signal for body acceleration from X-Axis| Numeric Value|
| tBodyAccJerk_mean_Y | Mean of the Jerk signal for body acceleration from Y-Axis| Numeric Value|
| tBodyAccJerk_mean_Z | Mean of the Jerk signal for body acceleration from Z-Axis| Numeric Value|
| tBodyAccJerk_std_X | Standard Deviation of the Jerk signal for body acceleration from X-Axis| Numeric Value|
| tBodyAccJerk_std_Y | Standard Deviation of the Jerk signal for body acceleration from Y-Axis| Numeric Value|
| tBodyAccJerk_std_Z | Standard Deviation of the Jerk signal for body acceleration from Z-Axis| Numeric Value|   
| tBodyGyro_mean_X | Mean of the angular velocity from X-Axis| Numeric Value|
| tBodyGyro_mean_Y | Mean of the angular velocity from Y-Axis| Numeric Value|
| tBodyGyro_mean_Z | Mean of the angular velocity from Z-Axis| Numeric Value|
| tBodyGyro_std_X | Standard Deviation of the angular velocity from X-Axis| Numeric Value|
| tBodyGyro_std_Y | Standard Deviation of the angular velocity from Y-Axis| Numeric Value|
| tBodyGyro_std_Z | Standard Deviation of the angular velocity from Z-Axis| Numeric Value|
| tBodyGyroJerk_mean_X | Mean of the Jerk signal for angular velocity from X-Axis| Numeric Value|
| tBodyGyroJerk_mean_Y | Mean of the Jerk signal for angular velocity from Y-Axis| Numeric Value|
| tBodyGyroJerk_mean_Z | Mean of the Jerk signal for angular velocity from Z-Axis| Numeric Value|
| tBodyGyroJerk_std_X |  Standard Deviation of the Jerk signal for angular velocity from X-Axis| Numeric Value|
| tBodyGyroJerk_std_Y |  Standard Deviation of the Jerk signal for angular velocity from Y-Axis| Numeric Value|
| tBodyGyroJerk_std_Z |  Standard Deviation of the Jerk signal for angular velocity from Z-Axis| Numeric Value|
| tBodyAccMag_mean | Mean of the Magnitude for body acceleration| Numeric Value|
| tBodyAccMag_std | Standard Deviation of the Magnitude for body acceleration| Numeric Value|
| tGravityAccMag_mean | Mean of the Magnitude for gravity acceleration| Numeric Value|
| tGravityAccMag_std | Standard Deviation of the Magnitude for gravity acceleration| Numeric Value|
| tBodyAccJerkMag_mean | Mean of the Magnitude from the Jerk signal for body acceleration| Numeric Value|
| tBodyAccJerkMag_std | Standard Deviation of the Magnitude from the Jerk signal for body acceleration| Numeric Value|
| tBodyGyroMag_mean | Mean of the Magnitude for angular velocity| Numeric Value|
| tBodyGyroMag_std | Standard Deviation of the Magnitude for angular velocity| Numeric Value||
| tBodyGyroJerkMag_mean | Mean of the Magnitude from the Jerk signal for angular velocity| Numeric Value|
| tBodyGyroJerkMag_std | Standard Deviation of the Magnitude from the Jerk signal for angular velocity| Numeric Value|
| fBodyAcc_mean_X |  Mean of the body acceleration from X-Axis| Numeric Value|
| fBodyAcc_mean_Y |  Mean of the body acceleration from Y-Axis| Numeric Value|
| fBodyAcc_mean_Z |  Mean of the body acceleration from Z-Axis| Numeric Value|
| fBodyAcc_std_X |  Standard Deviation of the body acceleration from X-Axis| Numeric Value|
| fBodyAcc_std_Y |  Standard Deviation of the body acceleration from Y-Axis| Numeric Value|
| fBodyAcc_std_Z |  Standard Deviation of the body acceleration from Z-Axis| Numeric Value|
| fBodyAcc_meanFreq_X |  Mean Frequency of the body acceleration from X-Axis| Numeric Value|
| fBodyAcc_meanFreq_Y |  Mean Frequency of the body acceleration from Y-Axis| Numeric Value|
| fBodyAcc_meanFreq_Z |  Mean Frequency of the body acceleration from Z-Axis| Numeric Value|
| fBodyAccJerk_mean_X |  Mean of the Jerk signal for body acceleration from X-Axis| Numeric Value|
| fBodyAccJerk_mean_Y |  Mean of the Jerk signal for body acceleration from Y-Axis| Numeric Value|
| fBodyAccJerk_mean_Z |  Mean of the Jerk signal for body acceleration from Z-Axis| Numeric Value|
| fBodyAccJerk_std_X |  Standard Deviation of the Jerk signal for body acceleration from X-Axis| Numeric Value|
| fBodyAccJerk_std_Y |  Standard Deviation of the Jerk signal for body acceleration from Y-Axis| Numeric Value|
| fBodyAccJerk_std_Z |  Standard Deviation of the Jerk signal for body acceleration from Z-Axis| Numeric Value|
| fBodyAccJerk_meanFreq_X |  Mean Frequency of the Jerk signal for body acceleration from X-Axis| Numeric Value|
| fBodyAccJerk_meanFreq_Y |  Mean Frequency of the Jerk signal for body acceleration from Y-Axis| Numeric Value|
| fBodyAccJerk_meanFreq_Z |  Mean Frequency of the Jerk signal for body acceleration from Z-Axis| Numeric Value|
| fBodyGyro_mean_X | Mean of the angular velocity from X-Axis| Numeric Value|
| fBodyGyro_mean_Y | Mean of the angular velocity from Y-Axis| Numeric Value|
| fBodyGyro_mean_Z | Mean of the angular velocity from Z-Axis| Numeric Value|
| fBodyGyro_std_X | Standard Deviation of the angular velocity from X-Axis| Numeric Value|
| fBodyGyro_std_Y | Standard Deviation of the angular velocity from Y-Axis| Numeric Value|
| fBodyGyro_std_Z | Standard Deviation of the angular velocity from Z-Axis| Numeric Value|
| fBodyGyro_meanFreq_X | Mean Frequency of the angular velocity from X-Axis| Numeric Value|
| fBodyGyro_meanFreq_Y | Mean Frequency of the angular velocity from Y-Axis| Numeric Value|
| fBodyGyro_meanFreq_Z | Mean Frequency of the angular velocity from Z-Axis| Numeric Value|
| fBodyAccMag_mean | Mean of the Magnitude for body acceleration| Numeric Value|
| fBodyAccMag_std | Standard Deviation of the Magnitude for body acceleration| Numeric Value|
| fBodyAccMag_meanFreq | Mean Frequency of the Magnitude for body acceleration| Numeric Value|
| fBodyBodyAccJerkMag_mean | Mean of the Magnitude from the Jerk signal for body acceleration| Numeric Value|
| fBodyBodyAccJerkMag_std | Standard Deviation of the Magnitude from the Jerk signal for body acceleration| Numeric Value|
| fBodyBodyAccJerkMag_meanFreq | Mean Frequency of the Magnitude from the Jerk signal for body acceleration| Numeric Value|
| fBodyBodyGyroMag_mean | Mean of the Magnitude for angular velocity| Numeric Value|
| fBodyBodyGyroMag_std | Standard Deviation of the Magnitude for angular velocity| Numeric Value|
| fBodyBodyGyroMag_meanFreq | Mean Frequency of the Magnitude for angular velocity| Numeric Value|
| fBodyBodyGyroJerkMag_mean | Mean of the Magnitude from the Jerk signal for angular velocity| Numeric Value|
| fBodyBodyGyroJerkMag_std | Standard Deviation of the Magnitude from the Jerk signal for angular velocity| Numeric Value|
| fBodyBodyGyroJerkMag_meanFreq | Mean Frequency of the Magnitude from the Jerk signal for angular velocity| Numeric Value|






